name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Create .env from environment
        run: |
          if [ "${{ vars.ENV }}" === "staging" ]; then
            echo "${{ secrets.STAGING_ENV }}" > src/config/.env
          elif [ "${{ vars.ENV }}" === "production" ]; then
            echo "${{ secrets.PRODUCTION_ENV }}" > src/config/.env
          else
            echo "Unknown ENV: ${{ vars.ENV }}"
            exit 1
          fi
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
